main: plugin.mcsl.MainClass
version: 0.1.2-beta
name: MinecraftServerLauncher
description: Official Minecraft Server Launcher plugin for external connection
author: S3nS3IW00
website: https://mcsl.app

commands:
  mcserverlauncher:
    aliases: [mcsl]
    usage: <command>
    default: op
    description: Main command that shows the arguments

permissions:
  mcserverlauncher.command:
    default: op