main: plugin.mcsl.MainClass
version: 0.1.0-beta
name: MinecraftServerLauncher
description: Official Minecraft Server Launcher plugin
author: S3nS3IW00
website: https://mcsl.app

commands:
  mcserverlauncher:
    aliases: [mcsl]
    usage: <command>
    default: op
    description: Main command of Minecraft Server Launcher

permissions:
  mcserverlauncher.command:
    default: op